[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.0"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-rocm" }
torchvision = { index = "pytorch-rocm" }
torchaudio = { index = "pytorch-rocm" }


[project]
name = "ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=5.0.0",
    "numpy>=2.4.6",
    "tensorboard>=2.21.0",
    "tokenizers>=0.23.1",
    "torch>=2.3.1",
    "tqdm>=4.67.3",
    "transformers>=4.17.0",
    "wandb>=0.28.1",
]
